[View in Colaboratory](https://colab.research.google.com/github/udithv/DeepLearning/blob/master/tensorflow_basics.ipynb)

#Tf Basics

In [0]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.10.1


In [0]:
hello = tf.constant("Hello")

In [0]:
world = tf.constant("World")

In [5]:
type(world)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [8]:
result

b'HelloWorld'

In [0]:
a = tf.constant(10)

In [0]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result = sess.run(a+b)

In [15]:
result

30

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4), 10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4, 4))

In [0]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [0]:
myrandu = tf.random_uniform((4,4),minval=0, maxval=1)

In [0]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [0]:
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0.31294203 0.51946604 0.5359442  0.9900025 ]
 [0.9906126  0.09281933 0.8154689  0.09130168]
 [0.14155066 0.1015892  0.6959411  0.1251247 ]
 [0.41950178 0.03383601 0.52311575 0.2998259 ]]


[[0.3423891  0.463583   0.7945436  0.14830482]
 [0.5153742  0.13657272 0.6918813  0.79473126]
 [0.92217255 0.874725   0.8032564  0.65239966]
 [0.33243585 0.29671264 0.12043679 0.21116781]]




In [0]:
a = tf.constant([ [1, 2],
                  [3, 4]])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10], [100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a, b)

In [33]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [34]:
result.eval()

array([[210],
       [430]], dtype=int32)

#Graphs

In [0]:
n1 = tf.constant(1)

In [0]:
n2 = tf.constant(2)

In [0]:
n3 = n1 + n2

In [0]:
with tf.Session() as sess:
  result = sess.run(n3)

In [39]:
result

3

In [40]:
print(tf.get_default_graph())

In [0]:
g = tf.Graph()

In [42]:
print(g)

In [0]:
graph_one = tf.get_default_graph()

In [45]:
print(graph_one)


In [0]:
graph_two = tf.Graph()

In [47]:
print(graph_two)

In [48]:
with graph_two.as_default():
  print(graph_two is tf.get_default_graph())

True


In [49]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [0]:
sess.close()

In [51]:
sess = tf.InteractiveSession()


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [0]:
sess.close()

In [0]:
sess.close()


In [0]:
my_tensor = tf.random_uniform((4,4), 0, 1)

In [58]:
my_tensor


<tf.Tensor 'random_uniform_2:0' shape=(4, 4) dtype=float32>

In [0]:
my_var = tf.Variable(initial_value=my_tensor)

In [60]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [61]:
sess.run(my_var)

FailedPreconditionError: ignored

In [0]:
init = tf.global_variables_initializer()

In [0]:
sess.run(init)

In [64]:
sess.run(my_var)

array([[0.09771621, 0.33122742, 0.52665555, 0.10087347],
       [0.07768881, 0.73495567, 0.45133007, 0.27294624],
       [0.84368944, 0.6236131 , 0.16561079, 0.09641743],
       [0.9803096 , 0.09114039, 0.55840945, 0.6304952 ]], dtype=float32)

In [0]:
ph = tf.placeholder(tf.float32)